/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApplicationEnvironmentConfiguration'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApplicationEnvironmentConfiguration'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.ApplicationConfiguration = factory(root.dashboard.ApiClient, root.dashboard.ApplicationEnvironmentConfiguration);
  }
}(this, function(ApiClient, ApplicationEnvironmentConfiguration) {
  'use strict';




  /**
   * The ApplicationConfiguration model module.
   * @module model/ApplicationConfiguration
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>ApplicationConfiguration</code>.
   * @alias module:model/ApplicationConfiguration
   * @class
   * @param image {String} 
   * @param username {String} 
   * @param password {String} 
   * @param environment {module:model/ApplicationEnvironmentConfiguration} 
   */
  var exports = function(image, username, password, environment) {
    var _this = this;

    _this['image'] = image;
    _this['username'] = username;
    _this['password'] = password;
    _this['environment'] = environment;
  };

  /**
   * Constructs a <code>ApplicationConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/ApplicationConfiguration} obj Optional instance to populate.
   * @return {module:model/ApplicationConfiguration} The populated <code>ApplicationConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('image')) {
        obj['image'] = ApiClient.convertToType(data['image'], 'String');
      }
      if (data.hasOwnProperty('username')) {
        obj['username'] = ApiClient.convertToType(data['username'], 'String');
      }
      if (data.hasOwnProperty('password')) {
        obj['password'] = ApiClient.convertToType(data['password'], 'String');
      }
      if (data.hasOwnProperty('environment')) {
        obj['environment'] = ApplicationEnvironmentConfiguration.constructFromObject(data['environment']);
      }
    }
    return obj;
  }

  /**
   * @member {String} image
   */
  exports.prototype['image'] = undefined;
  /**
   * @member {String} username
   */
  exports.prototype['username'] = undefined;
  /**
   * @member {String} password
   */
  exports.prototype['password'] = undefined;
  /**
   * @member {module:model/ApplicationEnvironmentConfiguration} environment
   */
  exports.prototype['environment'] = undefined;



  return exports;
}));


