/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/AudioRequest', 'model/DisplayGlobalConfiguration', 'model/DisplayRequest', 'model/TouchRequest'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./AudioRequest'), require('./DisplayGlobalConfiguration'), require('./DisplayRequest'), require('./TouchRequest'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.AutomaticStoreRequest = factory(root.dashboard.ApiClient, root.dashboard.AudioRequest, root.dashboard.DisplayGlobalConfiguration, root.dashboard.DisplayRequest, root.dashboard.TouchRequest);
  }
}(this, function(ApiClient, AudioRequest, DisplayGlobalConfiguration, DisplayRequest, TouchRequest) {
  'use strict';




  /**
   * The AutomaticStoreRequest model module.
   * @module model/AutomaticStoreRequest
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>AutomaticStoreRequest</code>.
   * @alias module:model/AutomaticStoreRequest
   * @class
   * @param audio {Array.<module:model/AudioRequest>} 
   * @param display {Array.<module:model/DisplayRequest>} 
   * @param touch {Array.<module:model/TouchRequest>} 
   * @param displayGlobal {module:model/DisplayGlobalConfiguration} 
   */
  var exports = function(audio, display, touch, displayGlobal) {
    var _this = this;

    _this['audio'] = audio;
    _this['display'] = display;
    _this['touch'] = touch;
    _this['displayGlobal'] = displayGlobal;
  };

  /**
   * Constructs a <code>AutomaticStoreRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/AutomaticStoreRequest} obj Optional instance to populate.
   * @return {module:model/AutomaticStoreRequest} The populated <code>AutomaticStoreRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('audio')) {
        obj['audio'] = ApiClient.convertToType(data['audio'], [AudioRequest]);
      }
      if (data.hasOwnProperty('display')) {
        obj['display'] = ApiClient.convertToType(data['display'], [DisplayRequest]);
      }
      if (data.hasOwnProperty('touch')) {
        obj['touch'] = ApiClient.convertToType(data['touch'], [TouchRequest]);
      }
      if (data.hasOwnProperty('displayGlobal')) {
        obj['displayGlobal'] = DisplayGlobalConfiguration.constructFromObject(data['displayGlobal']);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/AudioRequest>} audio
   */
  exports.prototype['audio'] = undefined;
  /**
   * @member {Array.<module:model/DisplayRequest>} display
   */
  exports.prototype['display'] = undefined;
  /**
   * @member {Array.<module:model/TouchRequest>} touch
   */
  exports.prototype['touch'] = undefined;
  /**
   * @member {module:model/DisplayGlobalConfiguration} displayGlobal
   */
  exports.prototype['displayGlobal'] = undefined;



  return exports;
}));


