/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.CustomClaims = factory(root.dashboard.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The CustomClaims model module.
   * @module model/CustomClaims
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>CustomClaims</code>.
   * @alias module:model/CustomClaims
   * @class
   * @param domain {String} 
   * @param domainUser {String} 
   * @param role {String} 
   */
  var exports = function(domain, domainUser, role) {
    var _this = this;

    _this['domain'] = domain;
    _this['domainUser'] = domainUser;
    _this['role'] = role;
  };

  /**
   * Constructs a <code>CustomClaims</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/CustomClaims} obj Optional instance to populate.
   * @return {module:model/CustomClaims} The populated <code>CustomClaims</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('domain')) {
        obj['domain'] = ApiClient.convertToType(data['domain'], 'String');
      }
      if (data.hasOwnProperty('domainUser')) {
        obj['domainUser'] = ApiClient.convertToType(data['domainUser'], 'String');
      }
      if (data.hasOwnProperty('role')) {
        obj['role'] = ApiClient.convertToType(data['role'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} domain
   */
  exports.prototype['domain'] = undefined;
  /**
   * @member {String} domainUser
   */
  exports.prototype['domainUser'] = undefined;
  /**
   * @member {String} role
   */
  exports.prototype['role'] = undefined;



  return exports;
}));


