/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.DisplayConfiguration = factory(root.dashboard.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The DisplayConfiguration model module.
   * @module model/DisplayConfiguration
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>DisplayConfiguration</code>.
   * @alias module:model/DisplayConfiguration
   * @class
   * @param enabled {Boolean} 
   * @param mode {String} 
   * @param reflect {String} 
   * @param rotate {String} 
   * @param transform {String} 
   */
  var exports = function(enabled, mode, reflect, rotate, transform) {
    var _this = this;

    _this['enabled'] = enabled;
    _this['mode'] = mode;
    _this['reflect'] = reflect;
    _this['rotate'] = rotate;
    _this['transform'] = transform;
  };

  /**
   * Constructs a <code>DisplayConfiguration</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DisplayConfiguration} obj Optional instance to populate.
   * @return {module:model/DisplayConfiguration} The populated <code>DisplayConfiguration</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('enabled')) {
        obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
      }
      if (data.hasOwnProperty('mode')) {
        obj['mode'] = ApiClient.convertToType(data['mode'], 'String');
      }
      if (data.hasOwnProperty('reflect')) {
        obj['reflect'] = ApiClient.convertToType(data['reflect'], 'String');
      }
      if (data.hasOwnProperty('rotate')) {
        obj['rotate'] = ApiClient.convertToType(data['rotate'], 'String');
      }
      if (data.hasOwnProperty('transform')) {
        obj['transform'] = ApiClient.convertToType(data['transform'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Boolean} enabled
   * @default true
   */
  exports.prototype['enabled'] = true;
  /**
   * @member {String} mode
   */
  exports.prototype['mode'] = undefined;
  /**
   * @member {String} reflect
   * @default 'NO_REFLECT'
   */
  exports.prototype['reflect'] = 'NO_REFLECT';
  /**
   * @member {String} rotate
   * @default 'NO_ROTATE'
   */
  exports.prototype['rotate'] = 'NO_ROTATE';
  /**
   * @member {String} transform
   */
  exports.prototype['transform'] = undefined;



  return exports;
}));


