/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DisplayConfiguration'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DisplayConfiguration'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.DisplayRequest = factory(root.dashboard.ApiClient, root.dashboard.DisplayConfiguration);
  }
}(this, function(ApiClient, DisplayConfiguration) {
  'use strict';




  /**
   * The DisplayRequest model module.
   * @module model/DisplayRequest
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>DisplayRequest</code>.
   * @alias module:model/DisplayRequest
   * @class
   * @param displayId {String} 
   * @param configuration {Object.<String, module:model/DisplayConfiguration>} 
   */
  var exports = function(displayId, configuration) {
    var _this = this;

    _this['displayId'] = displayId;
    _this['configuration'] = configuration;
  };

  /**
   * Constructs a <code>DisplayRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/DisplayRequest} obj Optional instance to populate.
   * @return {module:model/DisplayRequest} The populated <code>DisplayRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('displayId')) {
        obj['displayId'] = ApiClient.convertToType(data['displayId'], 'String');
      }
      if (data.hasOwnProperty('configuration')) {
        obj['configuration'] = ApiClient.convertToType(data['configuration'], {'String': DisplayConfiguration});
      }
    }
    return obj;
  }

  /**
   * @member {String} displayId
   */
  exports.prototype['displayId'] = undefined;
  /**
   * @member {Object.<String, module:model/DisplayConfiguration>} configuration
   */
  exports.prototype['configuration'] = undefined;



  return exports;
}));


