/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.GenericReponse = factory(root.dashboard.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The GenericReponse model module.
   * @module model/GenericReponse
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>GenericReponse</code>.
   * The response schema for every &#x60;machine&#x60; API call
   * @alias module:model/GenericReponse
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>GenericReponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/GenericReponse} obj Optional instance to populate.
   * @return {module:model/GenericReponse} The populated <code>GenericReponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('code')) {
        obj['code'] = ApiClient.convertToType(data['code'], 'String');
      }
      if (data.hasOwnProperty('details')) {
        obj['details'] = ApiClient.convertToType(data['details'], 'String');
      }
      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], Object);
      }
    }
    return obj;
  }

  /**
   * Error code of the call
   * @member {String} code
   * @default '""'
   */
  exports.prototype['code'] = '""';
  /**
   * Error message
   * @member {String} details
   * @default '""'
   */
  exports.prototype['details'] = '""';
  /**
   * @member {Object} body
   */
  exports.prototype['body'] = undefined;



  return exports;
}));


