/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ApplicationConfiguration'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./ApplicationConfiguration'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.InstallRequest = factory(root.dashboard.ApiClient, root.dashboard.ApplicationConfiguration);
  }
}(this, function(ApiClient, ApplicationConfiguration) {
  'use strict';




  /**
   * The InstallRequest model module.
   * @module model/InstallRequest
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>InstallRequest</code>.
   * @alias module:model/InstallRequest
   * @class
   * @param services {Array.<module:model/ApplicationConfiguration>} 
   */
  var exports = function(services) {
    var _this = this;

    _this['services'] = services;
  };

  /**
   * Constructs a <code>InstallRequest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InstallRequest} obj Optional instance to populate.
   * @return {module:model/InstallRequest} The populated <code>InstallRequest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('services')) {
        obj['services'] = ApiClient.convertToType(data['services'], [ApplicationConfiguration]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:model/ApplicationConfiguration>} services
   */
  exports.prototype['services'] = undefined;



  return exports;
}));


