/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/CustomClaims'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CustomClaims'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.JwtVerifyResponse = factory(root.dashboard.ApiClient, root.dashboard.CustomClaims);
  }
}(this, function(ApiClient, CustomClaims) {
  'use strict';




  /**
   * The JwtVerifyResponse model module.
   * @module model/JwtVerifyResponse
   * @version 5.0.0
   */

  /**
   * Constructs a new <code>JwtVerifyResponse</code>.
   * JWT Verify Response
   * @alias module:model/JwtVerifyResponse
   * @class
   * @param uid {String} 
   * @param email {String} 
   * @param displayName {String} 
   * @param customClaims {module:model/CustomClaims} 
   * @param iat {Number} 
   * @param exp {Number} 
   * @param aud {String} 
   * @param iss {String} 
   * @param metadata {Object} 
   */
  var exports = function(uid, email, displayName, customClaims, iat, exp, aud, iss, metadata) {
    var _this = this;

    _this['uid'] = uid;
    _this['email'] = email;
    _this['displayName'] = displayName;
    _this['customClaims'] = customClaims;
    _this['iat'] = iat;
    _this['exp'] = exp;
    _this['aud'] = aud;
    _this['iss'] = iss;
    _this['metadata'] = metadata;
  };

  /**
   * Constructs a <code>JwtVerifyResponse</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/JwtVerifyResponse} obj Optional instance to populate.
   * @return {module:model/JwtVerifyResponse} The populated <code>JwtVerifyResponse</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uid')) {
        obj['uid'] = ApiClient.convertToType(data['uid'], 'String');
      }
      if (data.hasOwnProperty('email')) {
        obj['email'] = ApiClient.convertToType(data['email'], 'String');
      }
      if (data.hasOwnProperty('displayName')) {
        obj['displayName'] = ApiClient.convertToType(data['displayName'], 'String');
      }
      if (data.hasOwnProperty('customClaims')) {
        obj['customClaims'] = CustomClaims.constructFromObject(data['customClaims']);
      }
      if (data.hasOwnProperty('iat')) {
        obj['iat'] = ApiClient.convertToType(data['iat'], 'Number');
      }
      if (data.hasOwnProperty('exp')) {
        obj['exp'] = ApiClient.convertToType(data['exp'], 'Number');
      }
      if (data.hasOwnProperty('aud')) {
        obj['aud'] = ApiClient.convertToType(data['aud'], 'String');
      }
      if (data.hasOwnProperty('iss')) {
        obj['iss'] = ApiClient.convertToType(data['iss'], 'String');
      }
      if (data.hasOwnProperty('metadata')) {
        obj['metadata'] = ApiClient.convertToType(data['metadata'], Object);
      }
    }
    return obj;
  }

  /**
   * @member {String} uid
   */
  exports.prototype['uid'] = undefined;
  /**
   * @member {String} email
   */
  exports.prototype['email'] = undefined;
  /**
   * @member {String} displayName
   */
  exports.prototype['displayName'] = undefined;
  /**
   * @member {module:model/CustomClaims} customClaims
   */
  exports.prototype['customClaims'] = undefined;
  /**
   * @member {Number} iat
   */
  exports.prototype['iat'] = undefined;
  /**
   * @member {Number} exp
   */
  exports.prototype['exp'] = undefined;
  /**
   * @member {String} aud
   */
  exports.prototype['aud'] = undefined;
  /**
   * @member {String} iss
   */
  exports.prototype['iss'] = undefined;
  /**
   * @member {Object} metadata
   */
  exports.prototype['metadata'] = undefined;



  return exports;
}));


