/**
 * OakOS Dashboard API
 * The Dashboard API provides a secure way to remotely issue commands to OakOS devices. All endpoints are generated from the [OakOS Platform gRPC API](https://github.com/OakLabsInc/platform-protos) 
 *
 * OpenAPI spec version: 5.0.0
 * Contact: oakos@zivelo.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ForgetWifiRequest', 'model/WifiConfiguration'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ForgetWifiRequest'), require('../model/WifiConfiguration'));
  } else {
    // Browser globals (root is window)
    if (!root.dashboard) {
      root.dashboard = {};
    }
    root.dashboard.NetworkApi = factory(root.dashboard.ApiClient, root.dashboard.ForgetWifiRequest, root.dashboard.WifiConfiguration);
  }
}(this, function(ApiClient, ForgetWifiRequest, WifiConfiguration) {
  'use strict';

  /**
   * Network service.
   * @module api/NetworkApi
   * @version 5.0.0
   */

  /**
   * Constructs a new NetworkApi. 
   * @alias module:api/NetworkApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;



    /**
     * Add Wifi
     * Adds or overwrites configuration for connecting to a specific WiFi network. The host will then attempt to connect to the network whenever it is available. These settings are persisted until &#x60;ForgetWifi&#x60; is used.
     * @param {module:model/WifiConfiguration} body 
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.addWiFiWithHttpInfo = function(body, dashboardMachine) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling addWiFi");
      }

      // verify the required parameter 'dashboardMachine' is set
      if (dashboardMachine === undefined || dashboardMachine === null) {
        throw new Error("Missing the required parameter 'dashboardMachine' when calling addWiFi");
      }


      var pathParams = {
        'dashboardMachine': dashboardMachine
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/machine/{dashboardMachine}/network/AddWiFi', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Add Wifi
     * Adds or overwrites configuration for connecting to a specific WiFi network. The host will then attempt to connect to the network whenever it is available. These settings are persisted until &#x60;ForgetWifi&#x60; is used.
     * @param {module:model/WifiConfiguration} body 
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.addWiFi = function(body, dashboardMachine) {
      return this.addWiFiWithHttpInfo(body, dashboardMachine)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Forget Wifi
     * Removes stored WiFi configuration.
     * @param {module:model/ForgetWifiRequest} body 
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.forgetWiFiWithHttpInfo = function(body, dashboardMachine) {
      var postBody = body;

      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling forgetWiFi");
      }

      // verify the required parameter 'dashboardMachine' is set
      if (dashboardMachine === undefined || dashboardMachine === null) {
        throw new Error("Missing the required parameter 'dashboardMachine' when calling forgetWiFi");
      }


      var pathParams = {
        'dashboardMachine': dashboardMachine
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/machine/{dashboardMachine}/network/ForgetWiFi', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Forget Wifi
     * Removes stored WiFi configuration.
     * @param {module:model/ForgetWifiRequest} body 
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.forgetWiFi = function(body, dashboardMachine) {
      return this.forgetWiFiWithHttpInfo(body, dashboardMachine)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * List Known Wifi Networks
     * Lists the WiFi network configurations that are available to this host.
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.listKnownWiFiNetworksWithHttpInfo = function(dashboardMachine) {
      var postBody = null;

      // verify the required parameter 'dashboardMachine' is set
      if (dashboardMachine === undefined || dashboardMachine === null) {
        throw new Error("Missing the required parameter 'dashboardMachine' when calling listKnownWiFiNetworks");
      }


      var pathParams = {
        'dashboardMachine': dashboardMachine
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/machine/{dashboardMachine}/network/ListKnownWiFiNetworks', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * List Known Wifi Networks
     * Lists the WiFi network configurations that are available to this host.
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.listKnownWiFiNetworks = function(dashboardMachine) {
      return this.listKnownWiFiNetworksWithHttpInfo(dashboardMachine)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Info
     * Shows network information for all Ethernet and WiFi devices, including current network addresses and MAC addresses.
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.networkInfoWithHttpInfo = function(dashboardMachine) {
      var postBody = null;

      // verify the required parameter 'dashboardMachine' is set
      if (dashboardMachine === undefined || dashboardMachine === null) {
        throw new Error("Missing the required parameter 'dashboardMachine' when calling networkInfo");
      }


      var pathParams = {
        'dashboardMachine': dashboardMachine
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/machine/{dashboardMachine}/network/info', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Info
     * Shows network information for all Ethernet and WiFi devices, including current network addresses and MAC addresses.
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.networkInfo = function(dashboardMachine) {
      return this.networkInfoWithHttpInfo(dashboardMachine)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


    /**
     * Wifi Scan
     * Lists visible WiFi networks using the first available WiFi interface
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link Object} and HTTP response
     */
    this.wiFiScanWithHttpInfo = function(dashboardMachine) {
      var postBody = null;

      // verify the required parameter 'dashboardMachine' is set
      if (dashboardMachine === undefined || dashboardMachine === null) {
        throw new Error("Missing the required parameter 'dashboardMachine' when calling wiFiScan");
      }


      var pathParams = {
        'dashboardMachine': dashboardMachine
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = ['Authorization'];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Object;

      return this.apiClient.callApi(
        '/machine/{dashboardMachine}/network/WiFiScan', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType
      );
    }

    /**
     * Wifi Scan
     * Lists visible WiFi networks using the first available WiFi interface
     * @param {String} dashboardMachine 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link Object}
     */
    this.wiFiScan = function(dashboardMachine) {
      return this.wiFiScanWithHttpInfo(dashboardMachine)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }
  };

  return exports;
}));
